// gen-version.fun - regenerate src/core/version.inc.
//
// Usage (works from any directory, any host):
//   fun <repo>/src/prj/fun/gen-version.fun [YYYYMMDD] ["release"]
//
// Written in pure Fun (no shell, no git, no external tool), so the same script
// runs on Windows and Linux. It locates version.inc relative to its own path
// (argv[1]), so the current directory does not matter.
//
// The numeric stamp defaults to today's local date; the release string defaults
// to '9.0'. Pass them explicitly for a reproducible release stamp, e.g.
//   fun src/prj/fun/gen-version.fun 20260926 9.0
//
// Why the clock and not git: this is a deliberate, release-time action, and
// reading git's output portably would need a shell (Windows exec returns no
// stdout). Ordinary builds use the committed version.inc as is.

// --- arguments: 2.arg() = stamp, 3.arg() = release -------------------------
// (argv[0] is the interpreter, argv[1] is this script, so user args start at 2.)
var stamp = 2.arg();
var release = 3.arg();
if release = '' then release = '9.0'; end if;

// Validate the stamp: exactly 8 digits, else fall back to today.
var ok = stamp.length() = 8;
var j = 0;
while ok and j < 8 do
  var c = stamp[j];
  if c < '0' or c > '9' then ok = false; end if;
  j += 1;
end do;
if not ok then
  var d = 1.time().format('yyyy-mm-dd');   // e.g. 2026-09-26
  stamp = '';
  j = 0;
  while j < d.length() do
    var c = d[j];
    if c >= '0' and c <= '9' then stamp &= c; end if;
    j += 1;
  end do;
end if;

// --- locate src/core/version.inc from this script's own path ---------------
// Walk back from argv[1] to its directory (handles '/' and Windows '\').
var me  = 1.arg();
var dir = '';
var i   = me.length() - 1;
while i >= 0 and me[i] <> '/' and me[i] <> 92.toChar() do i -= 1; end do;
if i >= 0 then dir = me.substr(0, i + 1); end if;
var inc = dir & '../../../src/core/version.inc';

// --- render and write ------------------------------------------------------
var nl = 10.toChar();
var content =
  '// AUTO-GENERATED by src/prj/fun/gen-version.fun - do not edit by hand.' & nl &
  '// Regenerate:  fun src/prj/fun/gen-version.fun [YYYYMMDD] ["release"]'  & nl &
  '//'                                                                     & nl &
  '// funVersion: numeric build stamp, YYYYMMDD. Defaults to the day this was' & nl &
  '//   regenerated (or the explicit YYYYMMDD argument). Scripts probe the'   & nl &
  '//   running interpreter with N.time() for N in 2010..2099, or with the'    & nl &
  "//   'version' field of 'host'.arg(); both read this constant."           & nl &
  '// funRelease: curated language version string (README Version line),'   & nl &
  "//   default '9.0' (or the explicit second argument)."                   & nl &
  'funVersion = ' & stamp & ';' & nl &
  "funRelease = '" & release & "';" & nl;

inc.save(content);

?. 'gen-version: funVersion=' & stamp & ' funRelease=' & release & ' -> ' & inc;
