代码       ::= ( 语句 | 代码块 | 注释 )*

语句       ::= ( 变量 | 赋值 | 调用 | 输出 | 跳转 | 引用 ) ';'
变量       ::= 'var' 名字 ( 参数? '=' 算式 )?
赋值       ::= 左值 [+-*&]? '=' 算式
调用       ::= 左值 '(' 值表 ')'
输出       ::= '?' ( '.' | ',' | ':' )? 算式
跳转       ::= ( 'exit' | 'next' ) ( 'when' 算式 )?
             | 'return' 算式?
             | 'raise' 算式
引用       ::= 'use' 字符串 ( 'as' 名字 )?

代码块     ::= ( 条件 | 分支 | 循环 | 异常 | 函数 | 类 ) ';'
条件       ::= 'if' 算式 'then' 代码 ( 'elsif' 算式 'then' 代码 )* ( 'else' 代码 )? 'end' 'if'
分支       ::= 'case' 算式 'is' ( 'when' 算式 'do' 代码 )+ ( 'else' 代码 )? 'end' 'case'
循环       ::= 'loop' 代码 'end' 'loop'
             | ( 'while' | 'for' 名字 ( ( ':' 名字 )? ( ',' 名字 )? 'in' | '=' 算式 'to' ( 算式 'step' )? ) ) 算式 ( 'loop' 代码 'end' 'loop' | 'do' 代码 'end' 'do' )
异常       ::= 'try' 代码 ( 'except' 代码 )? ( 'finally' 代码 )? 'end' 'try'
函数       ::= 'fun' 名字 参数 代码 'end' 'fun'
类         ::= 'class' 名字 ( '=' 前值 )? 参数 代码 'end' 'class'

算式       ::= '(' 算式 ')'
             | ( 'bit'? 'not' | ( 参数 | 名字 )? '->' | 前值 点符 | 算式 算符 ) 算式
             | 算式 '|' 前值
             | ( 'fun'? 参数 )? '{' 代码 '}'
             | 'fun'? 调用
             | 'var' 名字
             | 'new' 数组
             | 左值
             | 常量
算符       ::= [&+-*/^]
             | 'div'
             | 'mod'
             | '!'? '='
             | [=!] '~'
             | '<' ( '<' | '=' | '>' )?
             | '>' ( '=' | '>' )?
             | 'in'
             | 'bit'? ( 'and' | 'or' | 'xor' )
点符       ::= '.' [~!#%^&*-+=\|<>/?]+
参数       ::= '(' ( 名字 ( ',' 名字 )* )? ')'
值表       ::= ( 值 ( ',' 值 )* )?
值         ::= ( ( 名字 | 字符串 ) ':' )? 算式
左值       ::= 前值
             | 索引
前值       ::= 名字 '?'?
             | ( 算式 '.' )+ ( 名字 '?'? | 字符串 )
索引       ::= 左值 '.'? '[' 算式 ']'
数组       ::= '[' 值表 ','? ']'
常量       ::= 数字
             | 字符串
             | 时间
             | 正则
             | 数组
             | 'true'
             | 'false'
             | 'null'
             | 'nil'
数字       ::= '-'? [0-9]+ ( '.' [0-9]+ )? ( [Ee] [+-]? [0-9]+ )?
             | '0' ( [Xx] [0-9A-Fa-f]+ | [Bb] [0-1]+ )
字符串     ::= "'" ( [^']* | "''" )* "'"
             | '"' ( [^"]* | '""' )* '"'
             | '`' ( [^`]* | '``' )* '`'
时间       ::= '@' 字符串
正则       ::= ( '/' [^\s/]+ '/' | '%' [^\s%]+ '%' | '$' 字符串 ) [gimsux]*
名字       ::= [$_@-Za-z] [$_@-Za-z0-9]*
注释       ::= ( '//' | '#' ) [^\n]* | '#*' .* '#'