del *.dcu /s /a
del *.ppu /s /a
del *.o /s /a
del *.s /s /a
del ~*.* /s /a
del *.~* /s /a
del *.ddp /s /a
del *.pdb /s /a
del *.stat /s /a
del *.local /s /a
del *.identcache /s /a
del *.projdata /s /a
del *.exe /s /a
del *.dll /s /a
del *.drc /s /a
del *.map /s /a
